name: causalml-rtd-py311
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.11
  - pandoc
  - sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-bibtex
  - nbsphinx
  - pip:
    - cython>=3.0.11
    - dill>=0.3.8
    - importlib-metadata>=8.5.0
    - joblib>=1.4.0
    - lightgbm>=4.5.0
    - matplotlib>=3.9.2
    - multiprocess>=0.70.16
    - numba>=0.60.0
    - numpy>=1.25.2
    - pandas>=2.2.2
    - pyro-api>=0.1.2
    - pyro-ppl>=1.9.1
    - scikit-learn>=1.6.0
    - scipy>=1.16.0
    - seaborn>=0.13.2
    - shap>=0.46.0
    - statsmodels>=0.14.5
    - xgboost>=2.1.3
